config/routes.rb
MorumbitourCom::Application.routes.draw do
  devise_for :users
  resources :users
  
  resources :reservas

  root :to => 'reservas#index'

end

app/models/reserva.rb
# encoding: UTF-8
class Reserva < ActiveRecord::Base
  validates_presence_of [:nome, :quantidade_de_pessoas, :dia_desejado, :horario_desejado], :on => :create, :message => "não deve ficar em branco"
  
  def self.proximas_saidas
    self.sum(:quantidade_de_pessoas, :group => [:dia_desejado, :horario_desejado])
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  
  def active_for_authentication? 
    super && staff? 
  end 

  def inactive_message 
    if !staff? 
      :not_approved 
    else 
      super # Use whatever other message 
    end 
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/reservas_controller.rb
class ReservasController < ApplicationController
  
  before_filter :authenticate_user!
  
  # GET /reservas
  # GET /reservas.json
  def index
    @reservas_por_saida = Reserva.proximas_saidas
    @reservas = Reserva.find(:all, :conditions => {dia_desejado: params[:dia_desejado], horario_desejado: params[:horario_desejado]}) unless params[:dia_desejado].nil?
                            
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @reservas }
    end
  end

  # GET /reservas/1
  # GET /reservas/1.json
  def show
    @reserva = Reserva.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @reserva }
    end
  end

  # GET /reservas/new
  # GET /reservas/new.json
  def new
    @reserva = Reserva.new(dia_desejado: params[:dia_desejado],
                           horario_desejado: params[:horario_desejado])

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @reserva }
    end
  end

  # GET /reservas/1/edit
  def edit
    @reserva = Reserva.find(params[:id])
  end

  # POST /reservas
  # POST /reservas.json
  def create
    @reserva = Reserva.new(params[:reserva])

    respond_to do |format|
      if @reserva.save
        format.html { redirect_to @reserva, notice: 'Reserva was successfully created.' }
        format.json { render json: @reserva, status: :created, location: @reserva }
      else
        format.html { render action: "new" }
        format.json { render json: @reserva.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /reservas/1
  # PUT /reservas/1.json
  def update
    @reserva = Reserva.find(params[:id])

    respond_to do |format|
      if @reserva.update_attributes(params[:reserva])
        format.html { redirect_to @reserva, notice: 'Reserva was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @reserva.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reservas/1
  # DELETE /reservas/1.json
  def destroy
    @reserva = Reserva.find(params[:id])
    @reserva.destroy

    respond_to do |format|
      format.html { redirect_to reservas_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def bootstrap_form_for(object, options = {}, &block)
    options[:builder] = BootstrapFormBuilder
    form_for(object, options, &block)
  end
end

app/helpers/reservas_helper.rb
module ReservasHelper
end

app/views/common/_flashes.html.erb
<% unless flash[:notice].blank? %>
  <div class="alert-message info">
    <%= content_tag :div, flash[:notice] %>
  </div>
<% end %>

<% unless flash[:error].blank? %>
  <div class="alert-message error">
    <%= content_tag :div, flash[:error] %>
  </div>
<% end %>

<% unless flash[:alert].blank? %>
  <div class="alert-message warning">
    <%= content_tag :div, flash[:alert] %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MorumbitourCom</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body style="padding-top: 60px">
  <div class="topbar">
    <div class="topbar-inner">
      <div class="container-fluid">
        <h3><%= link_to "MorumbiTour", "/" %></h3>
        <ul class="nav">
          <li><%= link_to "Reservas", reservas_path  %></li>
		</ul>
		<ul class="nav secondary-nav">
			<li><% if current_user %><%= link_to "Olá, #{current_user.email}", edit_user_registration_path(current_user)  %><% end %></li>
			<li><%= link_to "logout", destroy_user_session_path, :method => :delete  %></li>
		</ul>
      </div>
    </div>
  </div>
  <div class="container-fluid">
    <div class="sidebar">
      <div class="well">
        <h5>Nova Reserva</h5>
        <ul>
          <li><%= link_to "Nova reserva, clique aqui!", new_reserva_path  %></li>
		</ul>
      </div>    

	  <% unless @reservas_por_saida.nil? %>
      <div class="well">
        <h5>Próximas saídas</h5>
		<ul>
		<% @reservas_por_saida.each do |data_e_horario, quantidade| %>
		  <li>
			<%= link_to "#{DataEHorario.new(data_e_horario[0], data_e_horario[1]).to_s} (#{quantidade})", reservas_path(dia_desejado: data_e_horario[0], horario_desejado: data_e_horario[1])%> 
		    <b><%= link_to "+", new_reserva_path(dia_desejado: data_e_horario[0], horario_desejado: data_e_horario[1] ) %></b>
		  </li>
		<% end %>
		</ul>
      </div>
	  <% end %>
    </div>
    <div class="content">
	  <%= render :partial => 'common/flashes' %>
      <%= yield %>
    </div>
  </div>
</body>
</html>

app/views/reservas/_form.html.erb
    <%= f.label :nome, t("activerecord.attributes.reserva.nome", :default => "Nome"), :class => :label %>
    <%= f.text_field :nome, :class => 'text_field' %>

    <%= f.label :email, t("activerecord.attributes.reserva.email", :default => "Email"), :class => :label %>
    <%= f.text_field :email, :class => 'text_field' %>

    <%= f.label :telefone, t("activerecord.attributes.reserva.telefone", :default => "Telefone"), :class => :label %>
    <%= f.text_field :telefone, :class => 'text_field' %>

    <%= f.label :quantidade_de_pessoas, t("activerecord.attributes.reserva.quantidade_de_pessoas", :default => "Quantidade de pessoas"), :class => :label %>
    <%= f.number_field :quantidade_de_pessoas, :class => 'number_field' %>

    <%= f.label :dia_desejado, t("activerecord.attributes.reserva.dia_desejado", :default => "Dia desejado"), :class => :label %>
    <%= f.date_select :dia_desejado, :order => [:day, :month, :year], :class => 'date_select' %>

    <%= f.label :horario_desejado, t("activerecord.attributes.reserva.horario_desejado", :default => "Horario desejado"), :class => :label %>
    <%= f.select :horario_desejado, DataEHorario.horarios_disponiveis, :class => 'date_select' %>

    <%= f.label :observacoes_e_pedidos_especiais, t("activerecord.attributes.reserva.observacoes_e_pedidos_especiais", :default => "Observacoes e pedidos especiais"), :class => :label %>
    <%= f.text_field :observacoes_e_pedidos_especiais, :class => 'text_field' %>
<div class="actions">
  <button class="btn primary" type="submit">Save</button> or
	<%= link_to "Cancel", reservas_path %>
</div>

app/views/reservas/edit.html.erb
<%= bootstrap_form_for :reserva, :url => reservas_path, :html => { :class => :form } do |f| -%>
  <%= render :partial => "form", :locals => {:f => f} %>
<% end -%>

app/views/reservas/new.html.erb
<%= bootstrap_form_for :reserva, :url => reservas_path, :html => { :class => :form } do |f| -%>
  <%= render :partial => "form", :locals => {:f => f} %>
<% end -%>

app/views/reservas/show.html.erb
  <label class="label"><%= t("activerecord.attributes.reserva.nome", :default => t("activerecord.labels.nome", :default => "Nome")) %>:</label>
  <p><%= @reserva.nome %></p>

  <label class="label"><%= t("activerecord.attributes.reserva.email", :default => t("activerecord.labels.email", :default => "Email")) %>:</label>
  <p><%= @reserva.email %></p>

  <label class="label"><%= t("activerecord.attributes.reserva.telefone", :default => t("activerecord.labels.telefone", :default => "Telefone")) %>:</label>
  <p><%= @reserva.telefone %></p>

  <label class="label"><%= t("activerecord.attributes.reserva.quantidade_de_pessoas", :default => t("activerecord.labels.quantidade_de_pessoas", :default => "Quantidade de pessoas")) %>:</label>
  <p><%= @reserva.quantidade_de_pessoas %></p>

  <label class="label"><%= t("activerecord.attributes.reserva.dia_desejado", :default => t("activerecord.labels.dia_desejado", :default => "Dia desejado")) %>:</label>
  <p><%= @reserva.dia_desejado %></p>

  <label class="label"><%= t("activerecord.attributes.reserva.horario_desejado", :default => t("activerecord.labels.horario_desejado", :default => "Horario desejado")) %>:</label>
  <p><%= @reserva.horario_desejado %></p>

  <label class="label"><%= t("activerecord.attributes.reserva.observacoes_e_pedidos_especiais", :default => t("activerecord.labels.observacoes_e_pedidos_especiais", :default => "Observacoes e pedidos especiais")) %>:</label>
  <p><%= @reserva.observacoes_e_pedidos_especiais %></p>
<%= link_to "Back", reservas_path  %>

app/views/reservas_old/_form.html.erb
<%= form_for(@reserva) do |f| %>
  <% if @reserva.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@reserva.errors.count, "error") %> prohibited this reserva from being saved:</h2>

      <ul>
      <% @reserva.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nome %><br />
    <%= f.text_field :nome %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :telefone %><br />
    <%= f.text_field :telefone %>
  </div>
  <div class="field">
    <%= f.label :quantidade_de_pessoas %><br />
    <%= f.number_field :quantidade_de_pessoas %>
  </div>
  <div class="field">
    <%= f.label "Dia e horário desejado" %><br />
    <%= f.date_select :dia_desejado, :order => [:day, :month, :year] %> as <%= f.select :horario_desejado, DataEHorario.horarios_disponiveis %>
  </div>
  <div class="field">
    <%= f.label :observacoes_e_pedidos_especiais %><br />
    <%= f.text_field :observacoes_e_pedidos_especiais %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/reservas_old/_reservas.html.erb
<h2>Reservas do dia <%= @reservas.first.dia_desejado.strftime('%d/%m/%y') %> <%= @reservas.first.horario_desejado %></h2>

<table>
	<tt>
		<td>Nome</td>
		<td>Quant.</td>
		<td>Obs.</td>
	</tt>
	<% total_de_pessoas = 0 %>
<% @reservas.each do |reserva| %>
	<tr>
		<td><%= link_to reserva.nome, reserva %></td>
		<td><%= reserva.quantidade_de_pessoas%></td> 
		<% total_de_pessoas += reserva.quantidade_de_pessoas %>
		<td><%= reserva.observacoes_e_pedidos_especiais %></td>
	</tr>
<% end %>
	<tr class='last'>
		<td id='label_total_passageiros'>Total de passageiros</td>
		<td id='total_passageiros'><%= total_de_pessoas %></td>
		<td></td>
	</tr>
</table>

app/views/reservas_old/edit.html.erb
<h1>Editing reserva</h1>

<%= render 'form' %>

<%= link_to 'Show', @reserva %> |
<%= link_to 'Back', reservas_path %>

app/views/reservas_old/index.html.erb
<h1>Reservas</h1>

<h2>Nova Reserva</h2>

<%= link_to "criar nova reserva", new_reserva_path %>  

<h2>Próximas Saídas</h2>

<ul>
<% @reservas_por_saida.each do |data_e_horario, quantidade| %>
  <li>
	<%= link_to "#{DataEHorario.new(data_e_horario[0], data_e_horario[1]).to_s} (#{quantidade})", reservas_path(dia_desejado: data_e_horario[0], horario_desejado: data_e_horario[1])%> 
    <b><%= link_to "+", new_reserva_path(dia_desejado: data_e_horario[0], horario_desejado: data_e_horario[1] ) %></b>
  </li>
<% end %>
</ul>

<%= render 'reservas' unless @reservas.nil? %>

app/views/reservas_old/new.html.erb
<h1>New reserva</h1>

<%= render 'form' %>

<%= link_to 'Back', reservas_path %>

app/views/reservas_old/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Nome:</b>
  <%= @reserva.nome %>
</p>

<p>
  <b>Email:</b>
  <%= @reserva.email %>
</p>

<p>
  <b>Telefone:</b>
  <%= @reserva.telefone %>
</p>

<p>
  <b>Quantidade de pessoas:</b>
  <%= @reserva.quantidade_de_pessoas %>
</p>

<p>
  <b>Dia desejado:</b>
  <%= @reserva.dia_desejado %>
</p>

<p>
  <b>Horario desejado:</b>
  <%= @reserva.horario_desejado %>
</p>

<p>
  <b>Observacoes e pedidos especiais:</b>
  <%= @reserva.observacoes_e_pedidos_especiais %>
</p>


<%= link_to 'Edit', edit_reserva_path(@reserva) %> |
<%= link_to 'Back', reservas_path %>

app/views/users/shared/_links.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Sign in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>